import random
import re

import markovify

_corpus = [
    "Bad apple echoes through night of fire",
    "Fallen angel descends from crimson sky with dark flame",
    "Cosmic dream shattered by moonlight sonata echoes",
    "Screaming crescent shines across silent whisper void",
    "Shimmering darkness swallows the eternal frontier gates",
    "Dancing blade cuts through fading echo of time",
    "Flying genesis rises above sleeping dragon mountain",
    "Dreaming phoenix awakens the rising soul within",
    "Lost melody drifts into chaos theory abyss",
    "Mystic garden grows beside divine comedy stage",
    "Ancient saga written in cursed grimoire pages",
    "Twisted fable tells of crimson horizon dawn",
    "Azure abyss reflects the frozen cascade water",
    "Blazing eternity melts hollow sanctuary gates",
    "Shrine of despair guards temple of paradox",
    "Hollow atlas maps the void dancer path",
    "Ember crown glows with frost reign power",
    "Pixel requiem plays retro storm melody",
    "Neo babel tower reaches cyber ronin sky",
    "Sakura prophecy unfolds twilight brigade story",
    "Midnight revelry dances until dawn chorus sings",
    "Dusk wanderer follows aurora drift light",
    "Comet seeker joins meteor parade festival",
    "Starlight serenade serenades moonrise kingdom",
    "Sunfall legacy fades into quantum requiem",
    "Photon hymn harmonizes with neutron lullaby",
    "Nova burst paints nebula canvas with galaxy colors",
    "Cosmos drift orbits the helix garden spiral",
    "Spiral ocean swallows vortex hymn melody",
    "Labyrinth core unlocks enigma pulse code",
    "Rhythm echo reverberates through harmonics zero",
    "Dissonance rain falls on static bloom garden",
    "Wired heart connects to prism heart signal",
    "Crystal frequency tunes into obsidian tide",
    "Silver fuse ignites golden thread weave",
    "Scarlet veil covers indigo signal path",
    "Violet spark ignites ivory storm lightning",
    "Onyx dream fractures jade cipher code",
    "Ruby script decrypts sapphire rune magic",
    "Emerald code runs amber relay protocol",
    "Opal circuit activates pearl network node",
    "Diamond protocol initializes amethyst engine",
    "Quartz lattice structures garnet vessel hull",
    "Coral matrix sustains obsidian forge flame",
    "Mithril edge sharpens adamant will power",
    "Element zero charges tungsten soul battery",
    "Platinum wing carries bronze knight forward",
    "Iron maiden traps copper dawn light",
    "Silver fang bites gold experience reality",
    "Dark cherry blossoms fall on bitter chocolate",
    "Sugar melody plays honeycomb logic puzzle",
    "Vanilla nebula floats above strawberry panic",
    "Blueberry dawn breaks with lemon angel wings",
    "Peach nirvana found in matcha paradox",
    "Espresso storm brews mocha twilight clouds",
    "Latte horizon stretches beyond cappuccino drift",
    "Cocoa prophecy reveals dark rose petals",
    "Night march leads to silent spring valley",
    "Wild hunt rides through deep one ocean",
    "Elder sign wards off necronomicon curse",
    "Nyarlathotep crawls from azathoth dream",
    "Yog sothoth opens the gate of silver key",
    "Mountain of madness echoes with nameless city cries",
    "Endless summer repeats the final frontier journey",
    "Last horizon reveals first contact signal",
    "Zero gravity floats near absolute zero space",
    "Event horizon traps singularity dark matter",
    "Tachyon pulse triggers warp drive hyper drive",
    "Time paradox shifts world line divergence meter",
    "Reading steiner activates future gadget phone microwave",
    "Time leap creates deja vu mandela effect",
    "Butterfly effect causes ripple effect domino effect",
    "Snowball effect triggers placebo effect casimir effect",
    "Red shift blue shift phase shift paradigm shift",
    "Crimson saga unfolds beneath twilight horizon",
    "Neon ronin walks the cyber babel frontier",
    "Quantum lullaby drifts through obsidian garden",
    "Ethereal blossoms fall on shrine paradox",
    "Galaxy express departs from nova station",
    "Meteor garden grows under aurora borealis",
    "Sakura chronicle written by moonlight quill",
    "Crescent echo bounces off crystal fortress",
    "Hollow tide swallows ancient grimoire pages",
    "Divine melody resonates through cursed cathedral",
    "Luminous wraith haunts the frozen cosmos",
    "Dreaming specter guards the ember labyrinth",
    "Celestial brush paints aurora across nebula sky",
    "Void walker traverses the infinite helix",
    "Cosmic forge tempers the stellar blade",
    "Phantom requiem echoes in silent cathedral",
    "Dark chronicle unfolds beneath crimson aurora",
    "Azure requiem plays for fallen sanctuary",
    "Silent zenith overlooks the fading cosmos",
    "Whispering shadow dances with phantom star",
    "Cursed melody haunts the broken timeline",
    "Eternal paradox binds the forgotten realm",
    "Frost ember burns in eternal winter",
    "Broken sanctuary guards the lost horizon",
    "Silent storm rises from chaos void",
    "Dreaming specter walks the midnight path",
    "Crimson nightmare engulfs the hollow shrine",
    "Ancient prophecy awakens sleeping titan",
    "Void melody echoes through crystal dimension",
    "Phantom horizon stretches beyond twilight",
    "Cursed genesis rises from fallen star",
    "Dark aurora dances over silent abyss",
    "Forgotten requiem plays for broken soul",
    "Chaos echo reverberates through time",
    "Lost chronicle written in phantom ink",
    "Eternal storm guards the ancient gate",
    "Broken dream floats in endless void",
    "Silent paradox binds the cosmic thread",
]

_model = markovify.Text("\n".join(_corpus), state_size=2, well_formed=False)

_stopwords = frozenset(
    {
        "the",
        "a",
        "an",
        "of",
        "in",
        "on",
        "at",
        "to",
        "for",
        "with",
        "and",
        "or",
        "but",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "by",
        "from",
        "into",
        "through",
        "over",
        "under",
        "above",
        "below",
        "up",
        "down",
        "out",
        "off",
        "not",
        "no",
        "nor",
        "so",
        "yet",
        "both",
        "either",
        "neither",
        "each",
        "every",
        "all",
        "any",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "than",
        "too",
        "very",
        "its",
        "it",
        "he",
        "she",
        "they",
        "them",
        "his",
        "her",
        "their",
        "this",
        "that",
        "these",
        "those",
        "which",
        "who",
        "whom",
        "what",
    }
)


class SubdomainGenerator:
    @staticmethod
    def generate() -> str:
        for _ in range(20):
            sentence = _model.make_sentence(test_output=False)
            if sentence:
                cleaned = re.sub(r"[^a-z0-9\s]", "", sentence.lower()).strip()
                words = [w for w in cleaned.split() if w not in _stopwords]
                if len(words) >= 2:
                    num_words = random.choice([2, 3])
                    selected = random.sample(words, min(num_words, len(words)))
                    return "-".join(selected)
        return "bad-apple"
